[package]
name = "trouble-host"
version = "0.1.0"
edition = "2021"
description = "An async Rust BLE host"
license = "Apache-2.0 or MIT"
keywords = [
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
resolver = "2"

[dependencies]
bt-hci = { version = "0.1.0", features = ["embassy-time"] }
embedded-io-async = { version = "0.6" }
embassy-sync = "0.5"
embassy-time = "0.3"
embassy-futures = "0.1"
futures = { version = "0.3", default-features = false }
heapless = "0.8"

# Logging
log = { version = "0.4.16", optional = true }
defmt = {version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
embedded-io-adapters = { version = "0.6.1", features = ["tokio-1"] }
embedded-io-async = { version = "0.6.1" }
tokio-serial = "5.4"
env_logger = "0.11"
critical-section = { version = "1", features = ["std"] }
static_cell = "2.1.0"

[features]
defmt = [ "dep:defmt" ]
gatt = []

[patch.crates-io]
bt-hci = { git = "https://github.com/alexmoon/bt-hci.git", branch = "try-controller" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
