name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd host
          cargo check
          cargo fmt --check
          cargo clippy

      - name: Test
        run: |
          cd host
          cargo test --lib -- --nocapture

      - name: Build examples
        run: for i in nrf-sdc; do pushd examples/$i; cargo fmt --check && cargo clippy && cargo build --release; popd; done;
  integration-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          TEST_ADAPTER_ONE: /dev/ttyACM0
          TEST_ADAPTER_TWO: /dev/ttyACM1
        run: |
          cd host
          cargo test --test '*'
