name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd host
          cargo check
          cargo fmt --check
          cargo clippy

      - name: Test
        run: |
          cd host
          cargo test --lib -- --nocapture

  examples:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        example: [nrf-sdc, serial-hci, apache-nimble]
    steps:
      - uses: actions/checkout@v4

      - name: Build example ${{ matrix.example }}
        working-directory: examples/${{ matrix.example }}
        run: |
          cargo fmt --check
          cargo clippy
          cargo build --release
