name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd host
          cargo check
          cargo fmt --check
          cargo clippy

      - name: Test
        run: |
          cd host
          cargo test -- --nocapture

      - name: Build examples
        run: for i in nrf-sdc; do pushd examples/$i; cargo fmt --check && cargo clippy && cargo build --release; popd; done;
