name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add dependencies
        run: |
          sudo apt-get install --no-install-recommends libudev-dev
          wget -O ~/.cargo/bin/cargo-batch https://github.com/embassy-rs/cargo-batch/releases/download/batch-0.4.0/cargo-batch
          chmod +x ~/.cargo/bin/cargo-batch
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target_ci/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: CI
        run: |
          ./ci.sh
