name: Tests

on:
  workflow_dispatch:
    inputs:
      prNr:
        description: A PR number to build
        required: true

jobs:
  integration-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr checkout "${{ github.event.inputs.prNr }}"
      - name: Build
        env:
          TEST_ADAPTER_ONE: /dev/ttyACM0
          TEST_ADAPTER_TWO: /dev/ttyACM1
          RUST_LOG: info
        run: |
          cd host
          cargo test --test '*' -- --nocapture
