name: Tests

on:
  workflow_dispatch: {}

jobs:
  integration-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          TEST_ADAPTER_ONE: /dev/ttyACM0
          TEST_ADAPTER_TWO: /dev/ttyACM1
          RUST_LOG: info
        run: |
          cd host
          cargo test --test '*' -- --nocapture
